# Generated by Django 6.0.6 on 2026-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_leao", "0004_contapagar_juros"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="banco_pago",
            field=models.CharField(
                default="Definir",
                max_length=100,
                verbose_name="Banco / Meio de Pagamento",
            ),
        ),
    ]
