# Generated by Django 6.1.1 on 2026-09-06 05:38

import app_leao.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0017_tarefa_frequencia_tarefa_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(storage=app_leao.storages.GoogleDriveStorage, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='vendas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Vendas'),
        ),
    ]
