# Generated by Django 6.0.6 on 2026-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vencimento",
                    models.DateField(db_index=True, verbose_name="Data de Vencimento"),
                ),
                (
                    "fornecedor",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Fornecedor"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Categoria"
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        max_length=100, verbose_name="Banco / Meio de Pagamento"
                    ),
                ),
                (
                    "parcela",
                    models.CharField(
                        default="1/1", max_length=20, verbose_name="Parcela"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
            ],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "ordering": ["-vencimento"],
            },
        ),
    ]
