# Generated by Django 6.0.6 on 2026-06-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_leao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contapagar",
            name="parcela",
            field=models.CharField(default="", max_length=20, verbose_name="Status"),
        ),
    ]
