# Generated by Django 6.0.6 on 2026-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_leao", "0002_alter_contapagar_parcela"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="conciliado",
            field=models.CharField(
                blank=True,
                default="Não",
                max_length=20,
                null=True,
                verbose_name="Conciliado",
            ),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="status",
            field=models.CharField(
                blank=True, default="Pendente", max_length=30, verbose_name="Status"
            ),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="ultimo_pagamento",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Último Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="contapagar",
            name="parcela",
            field=models.CharField(
                default="1/1", max_length=20, verbose_name="Parcela"
            ),
        ),
    ]
