# Generated by Django 6.0.6 on 2026-06-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_leao", "0003_contapagar_conciliado_contapagar_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="juros",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Juros (R$)"
            ),
        ),
    ]
