# Generated by Django 6.0.6 on 2026-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_leao", "0006_fornecedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoSaldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome do Banco/Conta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta com Saldo",
                "verbose_name_plural": "Contas com Saldo",
            },
        ),
    ]
