# Generated by Django 4.2.30 on 2026-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0007_bancosaldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('grupo', models.TextField(blank=True, default='-', null=True, verbose_name='grupo')),
                ('tipo', models.CharField(default='-', max_length=50, verbose_name='Tipo de Categoria')),
                ('descricao', models.TextField(blank=True, default='-', null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoExtrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(db_index=True, max_length=100, verbose_name='Banco do Extrato')),
                ('data_banco', models.DateField(db_index=True, verbose_name='Data no Extrato')),
                ('descricao_ofx', models.CharField(max_length=255, verbose_name='Descrição / Memo do Banco')),
                ('valor_extrato', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor no Extrato (R$)')),
                ('fitid', models.CharField(max_length=100, unique=True, verbose_name='ID Único da Transação (FITID)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transação do Extrato',
                'verbose_name_plural': 'Transações do Extrato',
                'ordering': ['-data_banco'],
            },
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='banco_pago',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='conciliado',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='juros',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='ultimo_pagamento',
        ),
        migrations.AddField(
            model_name='bancosaldo',
            name='cnpj_unidade',
            field=models.CharField(default='-', max_length=50, verbose_name='cnpj_unidade'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='nota_fiscal',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='bancosaldo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='banco',
            field=models.CharField(max_length=100, verbose_name='Banco / Meio de Pagamento Previsto'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], db_index=True, default='Pendente', max_length=30),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Original (R$)'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ConciliacaoBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_pagar_id', models.IntegerField(db_index=True, verbose_name='ID da Conta do Sistema')),
                ('transacao_extrato_id', models.IntegerField(db_index=True, verbose_name='ID da Linha do Extrato')),
                ('data_conciliacao', models.DateField(db_index=True, verbose_name='Data Real do Pagamento')),
                ('banco_pago', models.CharField(max_length=100, verbose_name='Banco Efetivo do Pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conciliação Bancária',
                'verbose_name_plural': 'Conciliações Bancárias',
                'unique_together': {('conta_pagar_id', 'transacao_extrato_id')},
            },
        ),
    ]
