# Generated by Django 4.2.30 on 2026-07-24 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0008_categoria_transacaoextrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Inclusão'),
            preserve_default=False,
        ),
    ]
