# Generated by Django 4.2.30 on 2026-07-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0009_contapagar_data_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='linha_digitavel',
            field=models.CharField(blank=True, default='', max_length=57, null=True, verbose_name='Linha Digitável do Boleto'),
        ),
    ]
