# Generated by Django 4.2.30 on 2026-08-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0010_contapagar_linha_digitavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('abertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Abertura')),
                ('suprimento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Suprimento')),
                ('saidas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saídas')),
                ('troco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Troco')),
                ('total_dinheiro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total em Dinheiro')),
                ('sangria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sangria')),
            ],
            options={
                'verbose_name': 'Fechamento de Caixa',
                'verbose_name_plural': 'Fechamentos de Caixa',
                'ordering': ['-data'],
            },
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='parcela',
            field=models.CharField(default='01/01', max_length=20, verbose_name='Parcela'),
        ),
    ]
