# Generated by Django 4.2.30 on 2026-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0011_fechamentocaixa_alter_contapagar_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='vendas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Troco'),
        ),
    ]
