# Generated by Django 4.2.30 on 2026-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0012_fechamentocaixa_vendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade/Filial')),
                ('data_deposito', models.DateField(verbose_name='Data do Depósito')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Depositado')),
                ('destino', models.CharField(choices=[('BANCO', 'Conta Bancária'), ('COFRE', 'Cofre Central'), ('OUTRO', 'Outro')], default='BANCO', max_length=10, verbose_name='Destino do Depósito')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes_depositos/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-data_deposito', '-criado_em'],
            },
        ),
    ]
