# Generated by Django 4.2.30 on 2026-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0013_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='destino',
            field=models.CharField(choices=[('Bradesco (E-Commerce)', '58.390.674/0001-20'), ('Bradesco (Aeroporto)', '58.390.674/0002-00'), ('Bradesco (Baenão)', '58.390.674/0004-72'), ('Bradesco (Castanheira)', '58.390.674/0003-91'), ('Bradesco (Pátio Belém)', '58.390.674/0005-53')], default='BANCO', max_length=100, verbose_name='Destino do Depósito'),
        ),
    ]
