# Generated by Django 6.1 on 2026-08-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0015_alter_bancosaldo_id_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Detalhes')),
                ('unidade', models.CharField(choices=[('Geral', 'Geral / Todas'), ('Loja 02 - Aeroporto', 'Loja 02 - Aeroporto'), ('Loja 03 - Castanheira', 'Loja 03 - Castanheira'), ('Loja 04 - Baenão', 'Loja 04 - Baenão'), ('Loja 05 - Pátio Belém', 'Loja 05 - Pátio Belém')], default='Geral', max_length=100)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['status', 'data_limite', '-prioridade'],
            },
        ),
    ]
