# Generated by Django 6.1 on 2026-08-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0016_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='frequencia',
            field=models.CharField(choices=[('avulsa', 'Avulsa / Única'), ('diaria', 'Rotina Diária (Todo dia)'), ('semanal', 'Semanal (1x por semana)'), ('mensal', 'Mensal (Fechamento/Fiscal)')], default='diaria', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='setor',
            field=models.CharField(choices=[('financeiro', 'Financeiro / Controladoria'), ('caixa', 'Caixa / Tesouraria'), ('fiscal', 'Fiscal / Tributário'), ('estoque', 'Estoque / Depósito'), ('compras', 'Compras / Fornecedores'), ('rh', 'RH / Departamento Pessoal'), ('operacional', 'Operacional / Loja')], default='financeiro', max_length=30, verbose_name='Setor'),
        ),
    ]
